# Generated by Django 3.1.1 on 2020-09-14 18:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='serive_email_name',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
