# Generated by Django 3.1.1 on 2020-09-15 10:44

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20200914_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='page_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
