# Generated by Django 3.1.1 on 2020-09-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_serviceitem_page_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='page_title',
        ),
    ]
