# Generated by Django 3.1.1 on 2020-09-15 12:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_remove_serviceitem_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='nav_link',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
