# Generated by Django 3.1.1 on 2020-09-12 17:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='body',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='headline_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='headline_intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='headline_muted_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='headline_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
