# Generated by Django 3.1.1 on 2020-09-13 13:04

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200912_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='call_to_action_description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='call_to_action_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
