# Generated by Django 3.1.1 on 2020-09-09 12:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='headline',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
