# Generated by Django 3.1.1 on 2020-09-15 12:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200910_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='nav_link',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
