# Generated by Django 3.1.1 on 2020-09-13 13:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200913_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='skills_list',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
